public with sharing virtual class ComponentSearchControllerBase {
    /**--------------------------------------- DEPRECATED CLASS ---------------------------------------
    public MemberPageControllerBase pageController { get;
        set {
            if (value != null) {
                pageController = value;
                pageController.setComponentController(this);
            }
        }
    }
    */
}